# Generated by Django 4.1 on 2026-03-30 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("nome", models.CharField(max_length=120)),
                ("data_gasto", models.DateField()),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("ALIMENTACAO", "Alimentação"),
                            ("TRANSPORTE", "Transporte"),
                            ("MORADIA", "Moradia"),
                            ("SAUDE", "Saúde"),
                            ("LAZER", "Lazer"),
                            ("OUTROS", "Outros"),
                        ],
                        default="OUTROS",
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-data_gasto", "-criado_em"],
            },
        ),
    ]
