# Generated by Django 4.1 on 2026-03-30 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gastos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gasto",
            name="criado_por",
        ),
    ]
