# Generated by Django 5.2.12 on 2026-04-12 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto_Fixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=120)),
                ('data_compensacao', models.PositiveIntegerField(default=0)),
                ('classificacao', models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('TRANSPORTE', 'Transporte'), ('MORADIA', 'Moradia'), ('SAUDE', 'Saúde'), ('LAZER', 'Lazer'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('valor_provisonado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_criados_fixos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
