# Generated by Django 5.2.12 on 2026-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gastos", "0002_gasto_fixo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compromissos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("nome", models.CharField(max_length=120)),
                ("data_compromisso", models.DateField()),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("ALIMENTACAO", "Alimentação"),
                            ("TRANSPORTE", "Transporte"),
                            ("MORADIA", "Moradia"),
                            ("SAUDE", "Saúde"),
                            ("LAZER", "Lazer"),
                            ("OUTROS", "Outros"),
                        ],
                        default="OUTROS",
                        max_length=20,
                    ),
                ),
                (
                    "valor_provisonado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valor_pago", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Compromisso",
                "verbose_name_plural": "Compromissos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
