# Generated by Django 5.2.12 on 2026-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gastos", "0003_compromissos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compromissos",
            name="valor_pago",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
